#!/bin/bash

if [ -d "/vagrant" ]; then
    pushd /vagrant >/dev/null
fi

function banner {
    printf "\n+---------------------------------\n"
    printf "| building %s..." $1
    printf "\n+---------------------------------\n"
}

banner src
pushd src >/dev/null
make clean
make
sleep 1
popd >/dev/null

banner tools/dump
pushd tools/dump >/dev/null
make clean
make
popd >/dev/null

banner tests
pushd tests >/dev/null
make clean
make
../bin/tests
popd >/dev/null

if [ -d "/vagrant" ]; then
    popd >/dev/null
fi
